"""
@file 0002_perfumerawdata.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Django 6.0.5 on 2026-05-11 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(help_text='원본 JSON 파일명', max_length=255)),
                ('source_brand', models.CharField(help_text='원본 브랜드명', max_length=100)),
                ('raw_data', models.JSONField(default=dict, help_text='변형 전 원본 향수 JSON 문서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perfume', models.OneToOneField(help_text='정규화된 향수 레코드 참조', on_delete=django.db.models.deletion.CASCADE, related_name='raw_document', to='perfumes.perfume')),
            ],
            options={
                'verbose_name': 'Perfume Raw Data',
                'verbose_name_plural': 'Perfume Raw Data',
            },
        ),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: fix(docker): normalize startup script handling. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0002_perfumerawdata.py
