"""
@file 0003_perfumedata_remove_perfume_data.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


def copy_perfume_data(apps, schema_editor):
    """Perfume.data JSON을 새 PerfumeData 테이블로 복사한다."""
    Perfume = apps.get_model("perfumes", "Perfume")
    PerfumeData = apps.get_model("perfumes", "PerfumeData")

    rows = []
    for perfume in Perfume.objects.all().only("id", "data"):
        rows.append(PerfumeData(perfume_id=perfume.id, data=perfume.data or {}))

    if rows:
        PerfumeData.objects.bulk_create(rows, batch_size=500, ignore_conflicts=True)


def restore_perfume_data(apps, schema_editor):
    """rollback 시 PerfumeData.data를 기존 Perfume.data 필드로 복원한다."""
    Perfume = apps.get_model("perfumes", "Perfume")
    PerfumeData = apps.get_model("perfumes", "PerfumeData")

    for detail in PerfumeData.objects.all().only("perfume_id", "data"):
        Perfume.objects.filter(id=detail.perfume_id).update(data=detail.data or {})


class Migration(migrations.Migration):
    """Perfume.data를 별도 PerfumeData 모델로 분리하는 migration."""

    dependencies = [
        ("perfumes", "0002_perfumerawdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfumeData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.JSONField(default=dict, help_text="서비스용 향수 상세 JSON 문서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "perfume",
                    models.OneToOneField(
                        help_text="정규화된 향수 레코드 참조",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="perfumes.perfume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfume Data",
                "verbose_name_plural": "Perfume Data",
            },
        ),
        migrations.RunPython(copy_perfume_data, restore_perfume_data),
        migrations.RemoveField(
            model_name="perfume",
            name="data",
        ),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: fix(docker): normalize startup script handling. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0003_perfumedata_remove_perfume_data.py
