"""
@file 0005_remove_perfumeproductinfo_perfume_and_more.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Django 6.0.5 on 2026-05-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_perfumeproductinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumeproductinfo',
            name='perfume',
        ),
        migrations.RemoveField(
            model_name='perfumerawdata',
            name='perfume',
        ),
        migrations.AddField(
            model_name='perfume',
            name='data',
            field=models.JSONField(default=dict, help_text='상세 정보 (NoSQL 스타일)'),
        ),
        migrations.DeleteModel(
            name='PerfumeData',
        ),
        migrations.DeleteModel(
            name='PerfumeProductInfo',
        ),
        migrations.DeleteModel(
            name='PerfumeRawData',
        ),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: fix(docker): normalize startup script handling. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0005_remove_perfumeproductinfo_perfume_and_more.py
