"""
@file 0007_remove_source_url_from_raw_json.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-13

from django.db import migrations


def remove_source_url_from_raw_json(apps, schema_editor):
    """PerfumeRawData.raw_json 내부의 중복 source_url 필드를 제거한다."""
    PerfumeRawData = apps.get_model("perfumes", "PerfumeRawData")

    for row in PerfumeRawData.objects.all().iterator():
        raw_json = row.raw_json or {}
        if not isinstance(raw_json, dict) or "source_url" not in raw_json:
            continue

        raw_json.pop("source_url", None)
        row.raw_json = raw_json
        row.save(update_fields=["raw_json"])


def noop(apps, schema_editor):
    """역방향 migration에서 별도 복원 작업을 수행하지 않는다."""
    pass


class Migration(migrations.Migration):
    """raw_json 내부 source_url 제거를 적용하는 data migration."""

    dependencies = [
        ("perfumes", "0006_perfume_detail_raw_data_image"),
    ]

    operations = [
        migrations.RunPython(remove_source_url_from_raw_json, noop),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: feat(perfumes): persist perfume image assets. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0007_remove_source_url_from_raw_json.py
