"""
@file 0008_remove_perfumerawdata_source_url.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):
    """PerfumeRawData.source_url 컬럼을 제거하는 migration."""

    dependencies = [
        ("perfumes", "0007_remove_source_url_from_raw_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfumerawdata",
            name="source_url",
        ),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: feat(perfumes): persist perfume image assets. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0008_remove_perfumerawdata_source_url.py
