"""
@file 0009_perfumeimage_base64_data.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-13

from django.db import migrations, models


def copy_detail_base64_to_images(apps, schema_editor):
    """PerfumeDetail.data.image_asset.base64 값을 PerfumeImage.base64_data로 이전한다."""
    PerfumeImage = apps.get_model("perfumes", "PerfumeImage")

    for image in PerfumeImage.objects.select_related("perfume_detail").iterator():
        detail_data = image.perfume_detail.data or {}
        image_asset = detail_data.get("image_asset") or {}
        base64_data = image_asset.get("base64") or ""
        if not base64_data:
            continue
        image.base64_data = base64_data
        image.save(update_fields=["base64_data"])


class Migration(migrations.Migration):
    """PerfumeImage에 base64_data 필드를 추가하고 기존 값을 이전하는 migration."""

    dependencies = [
        ("perfumes", "0008_remove_perfumerawdata_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfumeimage",
            name="base64_data",
            field=models.TextField(blank=True, help_text="다운로드된 이미지의 Base64 인코딩 값"),
        ),
        migrations.RunPython(copy_detail_base64_to_images, migrations.RunPython.noop),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: feat(perfumes): persist perfume image assets. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0009_perfumeimage_base64_data.py
