"""
@file 0010_remove_image_asset_from_perfume_detail.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-13

from django.db import migrations


def remove_image_fields_from_detail_data(apps, schema_editor):
    """PerfumeDetail.data에서 이미지 관련 중복 필드를 제거한다."""
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        data = detail.data or {}
        if not isinstance(data, dict):
            continue

        changed = False
        for key in ("image_asset",):
            if key in data:
                data.pop(key, None)
                changed = True

        if changed:
            detail.data = data
            detail.save(update_fields=["data"])


class Migration(migrations.Migration):
    """PerfumeDetail JSON에서 image_asset/image_url 필드를 정리하는 migration."""

    dependencies = [
        ("perfumes", "0009_perfumeimage_base64_data"),
    ]

    operations = [
        migrations.RunPython(remove_image_fields_from_detail_data, migrations.RunPython.noop),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: feat(perfumes): persist perfume image assets. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0010_remove_image_asset_from_perfume_detail.py
