"""
@file 0011_normalize_perfume_detail_data.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-13

from django.db import migrations


DETAIL_DATA_KEYS = {
    "price",
    "description",
    "ingredients_raw",
    "notes",
    "accords",
    "keywords",
    "meta",
    "volume",
    "aura_profile",
    "standardized_notes",
    "representative_notes",
    "notes_parsed",
    "embedding_doc",
}


def normalize_detail_data(apps, schema_editor):
    """PerfumeDetail.data를 서비스에서 사용하는 허용 필드 집합으로 정규화한다."""
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        data = detail.data or {}
        if not isinstance(data, dict):
            continue

        normalized = {
            key: data[key]
            for key in DETAIL_DATA_KEYS
            if key in data
        }
        if normalized != data:
            detail.data = normalized
            detail.save(update_fields=["data"])


class Migration(migrations.Migration):
    """PerfumeDetail JSON payload를 정규화된 key set으로 축소하는 migration."""

    dependencies = [
        ("perfumes", "0010_remove_image_asset_from_perfume_detail"),
    ]

    operations = [
        migrations.RunPython(normalize_detail_data, migrations.RunPython.noop),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-14: fix(recommendations): split scent pyramid notes. (author: @nobrain711)
# 2026-05-13: feat(perfumes): persist perfume image assets. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0011_normalize_perfume_detail_data.py
