"""
@file 0012_remove_release_year_from_detail_meta.py
@role
Defines Django migration package state and schema transition code.

"""

# Generated by Codex on 2026-05-13

from django.db import migrations


def remove_release_year_from_detail_meta(apps, schema_editor):
    PerfumeDetail = apps.get_model("perfumes", "PerfumeDetail")

    for detail in PerfumeDetail.objects.all().iterator():
        data = detail.data or {}
        if not isinstance(data, dict):
            continue

        meta = data.get("meta")
        if not isinstance(meta, dict) or "release_year" not in meta:
            continue

        meta = dict(meta)
        meta.pop("release_year", None)
        data = dict(data)
        if meta:
            data["meta"] = meta
        else:
            data.pop("meta", None)

        detail.data = data
        detail.save(update_fields=["data"])


class Migration(migrations.Migration):

    dependencies = [
        ("perfumes", "0011_normalize_perfume_detail_data"),
    ]

    operations = [
        migrations.RunPython(remove_release_year_from_detail_meta, migrations.RunPython.noop),
    ]

# ----------------------------------------------------------------
# Update History
# 2026-05-18: git diff 기준 @file/@role header와 파일 책임을 기록하는 Update History/EOF footer 추가. (worker: @nobrain711)
# 2026-05-13: feat(perfumes): persist perfume image assets. (author: @nobrain711)
# ----------------------------------------------------------------

# EOF: 0012_remove_release_year_from_detail_meta.py
